import Head from "next/head";
import Image from "next/image";
import { FC } from "react";
import Navbar from "../navigation-routes/Navbar";

type UnauthenticatedLayoutProps = {
  pageTitle: string;
  children: JSX.Element | string;
};

const UnauthenticatedLayout: FC<UnauthenticatedLayoutProps> = (props) => {
  return (
    <>
      <Head>
        <title>{props.pageTitle} - Toko Alat Kesehatan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="min-h-screen p-16 flex flex-1 justify-center bg-gray-100 items-center">
        {props.children}
      </main>

      <footer className="flex flex-1 p-4 shadow-lg justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default UnauthenticatedLayout;
